/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.10.2/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    `java-library`
    `maven-publish`
    signing
}

group = "jp.vemi"
version = "1.0.0"

repositories {
    mavenCentral()
}

dependencies {
    // Jackson依存
    implementation("com.fasterxml.jackson.core:jackson-databind:2.19.2")

    // Additional dependencies for enhanced functionality
    api(libs.commons.math3)
    implementation(libs.guava)

    // テスト依存
    testImplementation(libs.junit.jupiter)
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    // Set target compatibility to Java 8 for maximum compatibility
    // This allows the library to run on Java 8+ while being built with Java 17+
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
    
    // Generate sources and javadoc JARs required for Maven Central
    withSourcesJar()
    withJavadocJar()
}

tasks {
    // Slim JAR（デフォルト・推奨）- 依存関係を含まない軽量版
    jar {
        archiveClassifier.set("")
        archiveFileName.set("jackson-databind-jsonc-${project.version}.jar")
        manifest {
            attributes(mapOf(
                "Implementation-Title" to "jackson-databind-jsonc",
                "Implementation-Version" to project.version,
                "Automatic-Module-Name" to "jp.vemi.jsoncmapper",
                "Multi-Release" to "true"
            ))
        }
    }
    
    // Fat JAR（推奨）- Jackson関連のみ含む最小限の自己完結型
    val fatJar = register<Jar>("fatJar") {
        archiveClassifier.set("all")
        archiveFileName.set("jackson-databind-jsonc-${project.version}-all.jar")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        
        from(sourceSets.main.get().output)
        
        // Jackson関連のみ含める（Guava, Commons-Mathは除外）
        from({
            configurations.runtimeClasspath.get()
                .filter { it.name.contains("jackson") && it.name.endsWith("jar") }
                .map { zipTree(it) }
        }) {
            exclude("META-INF/*.SF")
            exclude("META-INF/*.DSA")
            exclude("META-INF/*.RSA")
            exclude("META-INF/DEPENDENCIES")
            exclude("META-INF/LICENSE*")
            exclude("META-INF/NOTICE*")
        }
        
        manifest {
            attributes(mapOf(
                "Implementation-Title" to "jackson-databind-jsonc (All-in-One)",
                "Implementation-Version" to project.version,
                "Multi-Release" to "true"
            ))
        }
    }
    
    // All-in-One JAR（エンタープライズ環境向け）- shadowJar互換性のため残す
    val shadowJar = register<Jar>("shadowJar") {
        archiveClassifier.set("shadow")
        archiveFileName.set("jackson-databind-jsonc-${project.version}-shadow.jar")
        duplicatesStrategy = DuplicatesStrategy.EXCLUDE
        
        from(sourceSets.main.get().output)
        
        // Jackson関連のみ含める（Guava, Commons-Mathは除外）
        from({
            configurations.runtimeClasspath.get()
                .filter { it.name.contains("jackson") && it.name.endsWith("jar") }
                .map { zipTree(it) }
        }) {
            exclude("META-INF/*.SF")
            exclude("META-INF/*.DSA")
            exclude("META-INF/*.RSA")
            exclude("META-INF/DEPENDENCIES")
            exclude("META-INF/LICENSE*")
            exclude("META-INF/NOTICE*")
        }
        
        manifest {
            attributes(mapOf(
                "Implementation-Title" to "jackson-databind-jsonc (All-in-One)",
                "Implementation-Version" to project.version,
                "Multi-Release" to "true"
            ))
        }
    }
    
    // 両方をビルド
    build {
        dependsOn(fatJar)
        dependsOn(shadowJar)
    }
    
    named<Test>("test") {
        useJUnitPlatform()
    }
}

// Check for publishing credentials
val ossrhUsername = project.findProperty("ossrhUsername") as String? ?: System.getenv("OSSRH_USERNAME")
val ossrhPassword = project.findProperty("ossrhPassword") as String? ?: System.getenv("OSSRH_PASSWORD")
val hasOssrhCredentials = !ossrhUsername.isNullOrEmpty() && !ossrhPassword.isNullOrEmpty()

// GPG Signing Configuration
signing {
    val signingKey = System.getenv("GPG_PRIVATE_KEY")
    val signingPassword = System.getenv("GPG_PASSPHRASE")
    val hasSigningCredentials = !signingKey.isNullOrEmpty() && !signingPassword.isNullOrEmpty()
    
    if (hasSigningCredentials) {
        useInMemoryPgpKeys(signingKey, signingPassword)
        sign(publishing.publications)
    } else {
        println("GPG signing credentials not found, artifacts will not be signed")
    }
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            from(components["java"])
            artifactId = "jackson-databind-jsonc"
            
            pom {
                name.set("Jackson-Databind-Jsonc")
                description.set("A Java library that extends Jackson's JsonMapper to handle JSONC (JSON with Comments) format")
                url.set("https://github.com/vemic/jackson-databind-jsonc")
                
                licenses {
                    license {
                        name.set("Apache License 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                
                developers {
                    developer {
                        id.set("vemic")
                        name.set("vemic")
                        url.set("https://github.com/vemic")
                    }
                }
                
                scm {
                    connection.set("scm:git:git://github.com/vemic/jackson-databind-jsonc.git")
                    developerConnection.set("scm:git:ssh://github.com:vemic/jackson-databind-jsonc.git")
                    url.set("https://github.com/vemic/jackson-databind-jsonc")
                }
            }
        }
        
        create<MavenPublication>("fatJar") {
            artifact(tasks.named("fatJar").get())
            artifactId = "jackson-databind-jsonc-all"
            
            pom {
                name.set("Jackson Databind JSONC (All-in-One)")
                description.set("JSONC (JSON with Comments) support for Jackson - All-in-One JAR with dependencies")
                url.set("https://github.com/vemic/jackson-databind-jsonc")
                
                licenses {
                    license {
                        name.set("Apache License 2.0")
                        url.set("https://www.apache.org/licenses/LICENSE-2.0")
                    }
                }
                
                developers {
                    developer {
                        id.set("vemic")
                        name.set("vemic")
                    }
                }
                
                scm {
                    connection.set("scm:git:git://github.com/vemic/jackson-databind-jsonc.git")
                    developerConnection.set("scm:git:ssh://github.com:vemic/jackson-databind-jsonc.git")
                    url.set("https://github.com/vemic/jackson-databind-jsonc")
                }
            }
        }
    }
}
